compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: /home1/shangsha/workspace/MGFM/MGFM-serving/serving/finetune/hpo/config/ds_config_z3.json
  deepspeed_multinode_launcher: standard
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
main_process_port: 29500
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false